name: Build LaTeX

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build LaTeX document
      run: make
    - name: Upload file
      run: make upload
